---
- name: yml file to gather all the facts
  hosts: all
  tasks:
    - name: print the facts
      debug:
        msg: The default IPv4 address of {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }}

