---
- name: handler usage
  hosts: linux
  become: true
  tasks:
  - name: copy apache configuration file
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/
    notify:
        - restart_apache
  handlers:
     - name: restart_apache
       service:
         name: httpd
         state: restarted
