---
- name : use of roles
  hosts: linux
  become: true

  pre_tasks:
    - debug:
        msg: 'Begining of web server configuration'
  roles:
    - apache_vhost

  post_tasks:
    - debug:
        msg: 'web server configuration is completed'
