---
- name: Ansible script for running the scripts in mysql database
  hosts: database
  become: true
  tasks:
    - name: Create a new database with name 'db_hodersea'
      mysql_db:
        name: db_hodersea
        login_user: root
        login_password: 
        state: present
      notify: download_script
  handlers:
    - name: download_script
      get_url:
        url: https://raw.githubusercontent.com/MadhaviBrc/SEA/master/db_hodersea.sql
        dest: /home/ansible/dbscripts/output/
      notify: run_script
    - name: run_script
      mysql_db:
        state: import
        name: all
        target: /home/ansible/dbscripts/output/db_hodersea.sql
